// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClHTskLqnmCdAglKRx9geS8ZOHa1e8dbE',
    appId: '1:532752559688:web:563f6bb17adff39eaf727d',
    messagingSenderId: '532752559688',
    projectId: 'praticare-fd7f8',
    authDomain: 'praticare-fd7f8.firebaseapp.com',
    databaseURL: 'https://praticare-fd7f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'praticare-fd7f8.appspot.com',
    measurementId: 'G-T8YK7RE587',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuWXSWe5_AMwR5nBUvqXCiioZ9e-i7U84',
    appId: '1:532752559688:android:e872445bdc052493af727d',
    messagingSenderId: '532752559688',
    projectId: 'praticare-fd7f8',
    databaseURL: 'https://praticare-fd7f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'praticare-fd7f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs-FSE_jOLxOP8dqkJu3GnScgGX1qqNxE',
    appId: '1:532752559688:ios:51b4e479647ee012af727d',
    messagingSenderId: '532752559688',
    projectId: 'praticare-fd7f8',
    databaseURL: 'https://praticare-fd7f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'praticare-fd7f8.appspot.com',
    iosBundleId: 'com.example.praticare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs-FSE_jOLxOP8dqkJu3GnScgGX1qqNxE',
    appId: '1:532752559688:ios:aaf67e1378133b05af727d',
    messagingSenderId: '532752559688',
    projectId: 'praticare-fd7f8',
    databaseURL: 'https://praticare-fd7f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'praticare-fd7f8.appspot.com',
    iosBundleId: 'com.example.praticare.RunnerTests',
  );
}
